development:
  host: localhost
  port: 5432
  adapter: postgresql
  encoding: unicode
  database: chat_app
  pool: 5
  username: zaf
  password: 'zaf'

  test:
  host: localhost
  port: 5432
  adapter: postgresql
  encoding: unicode
  database: chat_app
  pool: 5
  username: zaf
  password: 'zaf'
